# Generated by Django 2.0.2 on 2018-02-07 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistsong',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_artist', to='artist.Artist'),
        ),
        migrations.AlterField(
            model_name='artistsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_song', to='song.Song'),
        ),
    ]
